name: Nicknames
main: jasonw4331\Nicknames\Main
src-namespace-prefix: jasonw4331\Nicknames
version: 1.0.0
api: 4.0.0
description: "A plugin which allows players to change their display name"
author: "jasonw4331"

commands:
  nicknames:
    description: Give a nickname to someone
    usage: "/nick <nickname: string> [player: target]"
    permission: nicknames.use;nicknames.others
    aliases:
      - nick
      - nickname

permissions:
  nicknames.use:
    description: Allows you to nickname yourself!
    default: op
  nicknames.others:
    description: Allows you to nickname others!
    default: op